### ISSUE TITLE
弱弱问一句这个注册绑定是啥意思

### ISSUE THREAD

**Issue by THMonster** [nyfair/scripts#1]
QVQ

**Comment by nyfair** [comment]
这个不好明说，有个QQ群622811874。其实我现在也不怎么用，直接aria2多开点线程，单文件速度稳定在1.5M也能接受了

**Comment by IsoaSFlus** [comment]
@nyfair 我这里从分享链接获取下载地址用aria2c -s16 -x16 -k1M也能有1m的速度……好像也够用233
